package adventofcode.aoc2024.day12;


/**
 * https://adventofcode.com/2024/day/12
 */
public class Main2 {

    public static void main(String[] args) {

        String v = "OOOOO\n" +
                "OXOXO\n" +
                "OOOOO\n" +
                "OXOXO\n" +
                "OOOOO\n";

        String s =
                "RRRRIICCFF\n" +
                        "RRRRIICCCF\n" +
                        "VVRRRCCFFF\n" +
                        "VVRCCCJFFF\n" +
                        "VVVVCJJCFE\n" +
                        "VVIVCCJJEE\n" +
                        "VVIIICJJEE\n" +
                        "MIIIIIJJEE\n" +
                        "MIIISIJEEE\n" +
                        "MMMISSJEEE\n";

        String t = "SSSSSSSSQQQQQQQUUUUUUUUBBBBBBBBBBBBBBBBBBBBBNNNNNNNNVVVVVVOIIIIIIIIIIIIILLLLLLLLLLLLLLTTSSSSSSSSSGGGGGGGGGGGGGGGGGKKKKKKKKKJJJJJJJJJJJJJJJJJ\n" +
                "SSSSSSSSQQQQQQUUUUUUEUUUUSBBBBBBBBBBBBBBBBBVVNVGNGNVVVVVOOOIIIIIIIIIIIIILLLLLLLLLLLLLLLLSSSSSSSSSGGGGGGGGGGGGGGGGGKKKKKKKKKKJJJJJJJJJJJJJJJJ\n" +
                "SSSSSSSQQQQQQQQUUUUUUUUUUBBUBBBBBBBBBBBBBBVVVGGGGGNVVVVVOOOIIIIIIIIIIIIILLLLLLLLLLLLLLLSSSSSSSSSSSGGGGGGGGGGGGGGGGKKSKKKKKKJJJJJJJJJJJSJJSSJ\n" +
                "SKSKKSSKQQQQQUUUUUUUUUUUUUUUBBBBBBBBBBBBBBBVGRGGGGGVVVVOOOOOOOIIIIIIIIIILLLLLLLLLLLLLLLSSSSSSSSSSSGGGGGGGGGGGGGGGGKKSKKKKKJJJJJJJJJJJJSJSSSJ\n" +
                "SKKKKKSKQQQQQUUUUUUUUUUUUUUQBBBBBBBBBBBBBBBGGGGGGGCOOOOOOOOOOIIIIIIIIIIIILLLLLLLLLLLLLSSSSSSSSSSSSSOGGGGGGGGGGGGGGGKSSSKKJJJJJJJJJJJJSSSSSSJ\n" +
                "SKKKKKKKKKQQQUQQUUUUUUUUUUUQBBBBBBBBBBBBBGGGGGGGGCCCOOOOOOOOOIIOOIIIIIIIILLLLLLLLLLLLLLSSSSSSSSSSSSGGGGGGGGGGGGGGGGSSSSJJJJJJJJJJJJJJSSSSSSJ\n" +
                "KKKKKKKKKKQQQQQQUUUUUUUUUUUBBBBBBBBBBBBBGGGGGGGGGGKKZZOOOOOOOOOOOOIIIIIILLLLLLLLLLLLLLLLSSSSSSSSSSSSGGGGGGGGGGGGGSSSSAAJJJJJJJJJJJNNNNNSSSSS\n" +
                "KKKKKKKKKKQQQQQQQUUUUUUUUUBBBQBBBBBBBGGGGGGGGGGGKNKKKZOOOOOOOOOOOOIIIIIIILQLLLLLLLLLLOLLSSSSSSSSSSSGGGGGGGGGGGGGSSSSSAJJNJJJJJJOJJNNNNSSSSSS\n" +
                "DKKKKKKKKKQQQQQQQUUUUUUUUUBQQQBBBVBGGGGGGGGGGGGGKKKKKOOOOOOOOOOOOOOOIIIIIIQLLLLLLLLLLSSSSSSSSSSSSSSGGGGGGGGGGGGSSSSSSSILNLEEJEJJJJJNNNNNSSSS\n" +
                "DDKKKKKKQQQQQQQQQUUUUUUUQQQQQBBBBBCCGGGGGGGGGQGGAKKKKKOOOOOOOOOOOOOIIIIIILLLLLLLLLLLLSSSSSSSSSSSSSVVVVVGGGGGGGGSSSSSSIILLLEEEEJFJJNNNNNNSSSS\n" +
                "CCCKCCCCQQQQQQQQQUUUUUUUUUQQQQBBBBCCNGGGGGGGGGGGKKKKKPPOOOOOOOOOOOOOIIIIGLXXXXLLLLLSSSSSSSSSSSSSSSSVVVVVVGGSSSSSSSSSIIILLLLEEEEJJJNNNNNNNNSS\n" +
                "CCCCCCCCQQQQQQQQUUUUUUUUUAIQIQBBIICCNNGGGGGFGGKKKKKKKKKZOOOOOOOOOOOOIIIIGXXXXXXXSSSSSSSSSSSSSSSDSSSVVOVVVGVSSSSSSSSSILLLLLLEEEVVONNNNNNNYYYY\n" +
                "QCCCCCCCQQQQQQQUUUUUUUUUUIIIIIIKIIICNNGGGGFFFFFFFKKKKKZZOOOOOOOOOOOYIIIIIXXXXXXSSSSSSSSSSSSDDRSSSSSOOOVVVGVSSSSSSSSIILLLLLLLLVVVVBNNNNNYYYYY\n" +
                "QCCCCCCCQQQQQQIUUUUUUUUUIITIIIIKIININNNNNNNFFFFFKKKKZZZZOOOOOOOOOOOYYIIIXXXXXXXGSSSSSSSSSSSSDDUUSOOOOVVVVVVSASSYYYSLLLLLLLVVVVVVBBNNNNNNYYYY\n" +
                "QCCCCCCCCQQQQQIUUUKUUUMMMMMMIIIIIIIINNNNNNNNFFFFKKKZZZZZOOOOOOOOYYYYYIIIXXXXXXXGGSSSSSSSSSSSDUUUSGOOOVVVRRRSSSSYYYYLLLLLLLVVVVVVVBYNNNYYYYYY\n" +
                "QCCCCVVCCVQQQQQKKDKUUUMMMMMMMMMMMMINNNNNNNNEFEFFFKKKZZZZZOOOOOOOYYYYXXXXXXXXXXXGSSSSSSSSSSSSDDUUUOOOVOOVVVRRSRSSYYYYLLLLLLVVVVVVVVYYYNYYYYYY\n" +
                "QQCCVVVVVVQQQQQKKKKKKUMMMMMMMMMMMMNNNNNNNNNEEEFEEZZZZZZZZZOOOOOOYYYYXXXXXXXXKKKGGSSJSSSJSSSDDDDOOOOOOOOVRRRRSRRRRYYLLLLLVVVVVVVVVYYYYNYYYYYY\n" +
                "QQQQQVVVVQQQQQKKKKKKKKMMMMMMMMMMMMNNNNNNNEEEEEEEZZZZZZZZZOOOOOOOYYYYYXXXXXXKKKKKKKSJJJSJSJSDDDDOOOOOOOOVRRRRRRRRRRYYLVLVVVVVVVVVVVYYYYYYYYYY\n" +
                "QQQQVVVVVVQRQQKKKKKKKRMMMMMMMMMMMMNNNNNNNENNNEZZZZZZZZZZTTTTTTTTTYYXYXXXXXXKKKKKKJJJJJJJJJJDDDDDOOOOOOORLRRRRRRRRRRYYVVVVVVVVVVVVVYYYYYYYYYY\n" +
                "QQQQQQVVVVVQQQQKKKKKKKMMMMMMEEEEEEENNNNNNNNNNEEZZZZZZZZZTTTTTTTTTXXXXXXXXXKTKKKKKJJJJJJJJJJDDDDOOOOOYOORRRRRRRRRRRRRVVVVVVVVVVVVZZKYYYYYYYYY\n" +
                "QQQQQVVVVVKKQQKKKKKKKKMMMMMMEEEEEEENNNNNNNNNNNZZZZZZZZZYTTTTTTTTTXXXXXXXXXKKKKKKKJJJJJJJJJSSSOOOOOOOYRRRRRRRRRRRRRRRDDVVVVVVVVVVVZKYYYYYYYYY\n" +
                "QQQQQQQQQVKKKKKKKKKKKKKKKKWIEEEEEEENLLLNNLLFNZZZZZZZZZZZTTTTTTTTTXXXXXXXXKKKKKKKKJJJJJJJJSSSSSSSOOOOOORRRRRRRRRRRRRRDVVVVVVVVVVVVKKKKKYYYYYY\n" +
                "QQQQQQQVVVKKKKKKKKKKKKKKKKKKEEEEEEENLLLLLLFFNZZTTTTTTTTTTTTTTTTTTXXXXXXXXXKKKKKKKKJJJJJJJJSSSJJSOOOOOOORRRRRRRRRRRRRDVVVVVVVJJVVVKKKKKYYYYYY\n" +
                "IIIIIQQQVKKKKKKKKKKKKKKKKDDKEEEEEEENNYLLLLLLZZZTTTTTTTTTTTTTTTTTXXXXXXXXXXKKKKIKKJJJJJJJJJSJJJJOOOOOOOORRRRRRRRRRRRRDVVVVVVVVKVKKKKKKKKYYYYY\n" +
                "IIIIIQIVVVVVKKKKKKWKDKDDDDDDEEEEEEETTLLLLLLLZZZTTTTTTTTTTTTYOYYYXXXBXXXXXXXXKIIIKKKJJJJJJJJJJJJOROOOOOORRRRRRRRRRRRDDVVVVVVVUKKKKKKKKKKKYYYY\n" +
                "IIIIIIIVVVVVYKKKKKKDDDDDDDDDEEEEEEETTLLLLLLLLZTTTTTTTTTTTTTYYYYYYYBBBXXXXXXXXIIIKKKUJJJJJJJJJJJOOOOOOOOOOORRRRRRRRRDDVVVVVVUUUKKKKKKKKKKZYYY\n" +
                "IIIIIIVVVVVVKKKKKKKSDDDDDDEEEEEEEEEEELLLLLLLLZTTTTTTTTTTTTTYYYYYYEBBBBXXXXVVXKKKDKKUKKJJJJJJCCCCCOOOOOOOOORMRMRMMMDDDDDVVVUUUUKKKKKKKKKZZYYY\n" +
                "IIIIIIVVVVVVKIKKKKDDDDDDDDDEEEEEEEEEELLLLLLLETTTTTTTTTTTTYYYYYYYYYBBBBBXXXVVKKKKDKKKKKJJJJJJCCCCCOOOOOOOOOOMMMMMMMDDDDDDVVVUUUUKKKKKKKKKZOOY\n" +
                "IIIIIIIVVVVVKIKKKKDDDDDDDDDEEEEEEEEEEILLLLLLETTTTTTTTTTTTYYYYYYYYYYYTBBUXDVVKKKKKKKKKKKJJJXJCCCCCOOOOOOOOOOMMMMMMMDDDDSVVVUUUIIIIQKKKKKKZOOQ\n" +
                "JIJIIIIVVVVIIIIIIIIDDDDDDEDEEEEEEEEEEEEEELLLETTTTTTTTTTTTTTTTTTTTTYTTTUUUDDVKKKKKKKKKIXJJXXXCCCCCOOOOOOOORMMMMMMMMMDDSSSSUUIIIIIKKKKKKKOOOOQ\n" +
                "JJJJIIIVVIVVIIIIIIIIXXDDDEEEEEEEEEEEEEEEEQQQEETTTTTTTTTTTTTTTTTTTTTTTTUDDDQKKKKKKKKKXXXJJJXXCCCCCOOOOOOOOOMMMMMMMMMMDSSSSSSSIIIIKKKKKNKKOOQQ\n" +
                "JJJJJIIIIIIIIIIIMIIIXXEEEEEEEEEEEEEEEEEEEQQQEQTTTTTTTTTTTTTTTTTTTTTTTTUDDDDDDKKKKKKXXXXXXXXXCCCCCOOOOOOOOQMMMMMIMMMMSSSSSSSSIIIIIIKKKKKKOQQY\n" +
                "JJJJJIIIIIIIIIIIIIIXXXLEEEEEEEEEEEEEEEEEEQQQQQTTTTTTTTTTTTTTTTTTTTTTDDDDDDDDDKKKKKKXXXXXXXXCCCCCCCCCOOOOOOFMMFFMMMMHHSSSSSSSSIIIIIIKIKIIYYYY\n" +
                "JJJJJIIIIIIIIIIIIIXXXLLLLLEEEEEEEFREEEEEEQQQQQQTTTTTTTTTTTTTTTTTTTTTTDDDDDDDDDKKKKXXXXXXXXXCCCCCCCCCOOOFFFFFFFMMMMHHSSSSSSSSSIIIIIIIIIIIYYYY\n" +
                "JJJJJKIIIIIIKIIILQLLXLLLLLEEEEFFFFREEEEEEQQQQQQTTTTTTTTTTTTTTTTTTTTTTDDDDDDDKKKKKKKKXXXXXXXCCCCCCCCCCCFFFFFFFFFFMMMSSSSSSSSSIIIIIIIIIYYYYYYY\n" +
                "JJJJJKKKKKKKKRIYLLLLLLLLLLLEEEFFFFFEEEEEEQQQQQQTTTTTTTTTTTTTTDVDDDTTTTDDDDDDKKKKKKKKKXXXXXXCCCCCCCCCCCFFFFFFFFFFFFSSFSSSSSSSISSIIIIYYYYYYYYY\n" +
                "JJJJJKKKFFKKKKYYYLLLLLLLLLLEEFFFFFFEEEEEEQQQQQQTTTTTTTTTTTTDDDDDDDTTTTDDDDDDDKKKKKKKKXXXXXXXXUUUUUUCCCFFFFFFFFFFFFFFFSSSSSSSSSSIIIIIYYYYYYYY\n" +
                "JJKKKKKKKKKKYYYYYLLLLLLLLLLENNNFVFFFFFFQQQQQQQQQTTTTTNTTTTDDDDDDDDTTTDDDKDDKKKKKKKKKKXXDXHXOUUUUUUUCCCFFFFFFFZFFZFFFFFESFFCFSSKIIXIIYYYYYYYY\n" +
                "JJJJKKKKKKKKKKYYYYYLLLLLLLLLFFFFFFFFFFFQQQQQQQQQTTTTNNGNNNNNNNDDDTTEDDDKKKDKKKKKKKKKKKKKXUUUUUUUUUUCCCEEEFFFFZZZZFFFFFFUFFFFXSIICXIYYYYYYYYY\n" +
                "JJKKKKKKKKKKKKKKVVVKLLLLLLLLGFFFFFFFFFFFQQQQQQQQTTTTNNGGGGNNNNDQQEEEEEEKKKKKKKKKKKKKKKKXXUUUUUUUUUUEEEEEEEEZZZZZZFFFFFFFFFFFFNNICCYYYYYYYYYY\n" +
                "JJKKKKKKKKKKKKKVVVVVVLLLLLLLLQFFFFFFFFFFFFQQQQQQTTTTGGGGGNNNNEEEEEEEEEEEKKKKKKKLKKKKJJJXXUUUUUUUUEEEEEEEEEDZZZZZZZFFFFFFFFFFFFNFCCCYYYYYYYYY\n" +
                "JJKKKKKKKKKKKKVVVVVVVVLLFFLLLFFFFFFFFFFFFFQQQQQQTTTTGGGGGNNNNNEEEEEEEEEEKKKKKLKLLTTTTTJJUUUUUUUUUUEEEEEEEEEZZZZZZZFFFFFFFFFFFFFFCCCYYYYYYYYY\n" +
                "JJKKKKKKKKKKKVVVVVVVVVLLFFFLFFFFFFFFFFFCZFQQQQQQTTTGGGGGGGNNNNEEEEEEEEEEEEEEKLLLLTTTTTTJJUUUUUUUUUEEEEEEEEEZZZZZZFFFFFFFFFFFFFCCCCCYYYYYYYYY\n" +
                "JJJJJKKKKKKKKVVVVVVVVVLFFFFFFFFFFFFFFCCCQQQQQQQQTGTTGGGGGGGNNNEEEEEEEEEEEEELLLLDDTTTTTTJJUUUUUUUUUEEEEEEEEEZZZZZZZFFFFFFFFFFFFFCCCCYYYYYYYYY\n" +
                "JJJJJKKKXKKKKKVVVVVVVVFFFFFFFFFFFFFFFCCEOQQQGQQQGGGGGGGGGGGNNNNEEEEEEEEEEDLLLLLDDTTTTTTJJJUUUUUZUUUEEEEEEEEZZZZZZZZQQFFFFFFFFFCCCCCYYYYYYYYY\n" +
                "JDDDKKKXXXXKKVVVVVVVVVFFFFFFFFFFFFFFFFCEEEEGGQQQGGGGGGGGGGGGNNNEEEEEEEEEEDDYLDDDDTTTTTTJJJUUUUZZUUZZEEEEEEEZZZZZZZZZQQQFFFFFFFFCCCCYYYYYYYYY\n" +
                "JTDDIIXXXXXKKKVVVVVVFFFFFFFFFFFFFFFFCCCEEEGGGGQGGGGGGGGGGGGGNNNENEEEEEEEEDDDLDDDDTTTTTTJJJUUUOZZZZZZZEEEDDEZZZZZZZZZQQQFFFFEFFCCCCCYYYYYYYYY\n" +
                "JDDDXXXXXXXXXKKVVVIVFFFFFFFFFFFFFFFFCCCEEEEEGGGGGGGTGGGGGGGGNNNNNNNEEEDDDDDDDDDDDTTTTTTJJJOOOOZZZGZZZZEEZZZZZZZZZZZZNQQFHHHFFGCCCYYYYYXYYYYY\n" +
                "JJDDDXXXXXXXXKXFFFFVFFFFFFFFZZFFFFFBBBCEEEEGGGTGTGTTGGGGGGGGNNNNNNNDDDDDDDDDDDDDDTTTTTTJJJOOOOGGZGZZZZZZZZZZZZZZZZZQNQQFHHHGGGGGGTXYXXXYXYYY\n" +
                "JDDDDXXXXXXXXXXFFFFFBBBBBFFFZZOZFZBBBBBBTTTGTTTTTTTTGAAAAAAAAANNNNNNDDDDDDDDDDDOOTTTTTTTTTTTOOOGGGGGZGGZZZZZZMZZZZQQNQQFHGGGGGGGGTXYXXXXXXYB\n" +
                "JDDDDXXXXXXXXFFFFFFFBBBBBFFZZZZZFZZBBBBTTTTTTTTTTTTTTAAAAAAAAANNNNFFVDDDDDDDDDDDOTTTTTTTTTTTOOGGGGGGGGGZZGZBZZBZZNNNNQQFGGGGGGGGGXXXXXXXXXXB\n" +
                "JDDDYYXUXXXXXFFFFFFFBBBBBFZZZZZZZZZZBBBBTTTTTTTTTTTAAAAAAAAAAANNFFFFVVDDDDDDDDDDOLTTTTTTTTTTOOGGGGGGGGGGGGBBBBBBBNNNNQQQQCCGGGGGSSSXXXXXXXXB\n" +
                "JNJDYYUUUXXXXFXXXFFFBBBBBFZZZZZZZZZZZBBBBTTTTTTTTTCAAAAAAAAAAANFFFFFFFHDDNDDDDDDOLTTTTTTTTTTOOOGGGGGGGGGGGGBBBBBBBBNNNQCCCCGGGGGGSXXXXXXXXXX\n" +
                "JJJUUUUUUXXXXXXXXXFFBBBBBFZZZZZZZZZZZBZZBTTTTTTTTTAAAAAAAAAAAAFFFFFFFFHDDNNNDDDDDLTTTTTTTTTTOOGGGGGGGGGGGBBBBBBBBBNNNNNNCCCCGLGGSSXXXXXXWXXX\n" +
                "JJJXUJJUUXXXXXXXXDFFBBBBBFOZZZZZZZZZZZZZBBWWWTTTGGGGGGGGAANFFFFFFFFFFFHDFNNNDDDDDDTTTTTTTTTTTOGGGGGGGGGGGBBWBBBBBNNNNNNCCCCCGLLGGXXXXXXXXXXX\n" +
                "JJJUUUUUUUXXXXCXXFFFBBBBBFZZZZZZZZZZZZZZBBWWWWTTGGGGGGGGAAFFFFFFFFFFFFFFFNNNNNNPDOTTTTTTTTTTTOZGGGGGGGGWWWWWBWWWNNNNNNNNCCCCGLLGHHHXHHHXHHHX\n" +
                "GJUUUUUUUUXXXXCXXFGGBBBBBFZZZZZZZZZZZZZZZBBWWWTAGGGGGGGGAAFFFFFFFFFFFFFFFNNNNPPPDOTTTTTTTTTTTZZGGGGGGGWWWWWWWWWNNNNNNNNNNNCCGHHHHHHXHHHHHHHX\n" +
                "UUUUUUUUUUXXXXCVVFCGBBBBBJJZZZZZZZZZZZZZZBBWWWWAGGGGGGGGNNFFFFFFFFFFFFFFSNNNNNNDKOTTTTTTTTTTTZZZZGGGGGGWWWWWWWWWWNNNNNNNCCCGGHHHHHHHHHHHHHHH\n" +
                "UUUUUUUUUUUXCCCCCRCCCCCJJJJJZZZZZZZZZZBBBBBWWWWAGGGGGGGGNNNNFEFFFFFFFFFFFNNNNNNDDDDTTTTTTTTTTZZZZZGGGGGWWWWWWWWNNNNNNNNNNCCCGGGHHGGGHHHHHHHH\n" +
                "UUUUUUUUUUUUUCCCCCCCCCCCCJJZZZZZZZZZZBBBBBWWWWWAGGGGGGGGNNNNEELFFFFFFFFNNNNNNNNDDDDTTTTTTTTTTTTZGGGGGGGWWWWWWWWNNNNNNNNNCCCCGGGGGGGHHHHHHHHH\n" +
                "CUUUUUUUUUUUUUCCCCCCCCCCCCOZZZZZZZAZBBBBBBBWWWWAGGGGGGGGNNNEEELFFFFFFFFFNNNNNNNDDDDDDDDTTTTTTTTZZGGGGGWWWWWWWWWNNNNNNNNNNCCCGGGGGGGHHHHHHHHH\n" +
                "UUUUUUUUUUUUUBBCCCCCCCCCCCOZZZZZZAAABBBBBBIIWWIAGGGGGGGGNNNNEELFEAFFFFFFNNNNNNNNNDDDDDDTTTTTTTTZZGGGGWWWWWWWWWWNNNNNNNCCCCCCGGGGGGHHHQHHHHHH\n" +
                "MMUUBBUUUUBUBBBCCCCCCCCCCCOZZZZZZZAAAMBBBGGGGGGGGGGGGGGGKKEEEEEEEEEFFFNNNNNNNPNNNDDDDDDTTTTTTTTZGGGGGGWWWWWWWWWWNENNNGCCCCCCGGGGGGGHQQQHHHHH\n" +
                "MMUUUBBBBUBUBBBCCCCCCCCCCCOOOOOZOOOAAMMBBGGGGGGGGGGGGGIKKKKEEEEEEEEFFFFNNNNNNNNDDDDDDDDDKKZTTTTZZGGGGGGYWWWWWWWWEEGGMGCCCCCGGGGGGGGHHHQQHHHH\n" +
                "MMUUUBBBBBBBBBBCCCCCCCCCCOOOOOOOOOOOOMMMBGGGGGGGGGGGGGIIKKKKEEEEEEEEFFFNNNNNNNNDDDDDDDDDKKZTTTTZZZGXGYYYYWWWWWWWWWGOGGCCCCGGGGGGGHHHHQQQHHHH\n" +
                "MMUBSBBBBBBBBBBBBCCCCCCCOOOOOOOOOOOOMMMMMGGGGGGGGGGIIIIKKKKKEEEEVEEEFFFFNNNNNNNNNDDDDDDDKZZTTTTZZAYYYYYYYWWWWWWWWWGGGGCACCGGGGGGGHHHHQQQHQQQ\n" +
                "MBBBBBBBBBBBBBBBBBCCCCOOOOOOOOOOOOOOMMMMMGGGGGGGGGGIIIIKKKKKKKEEVVEEFFVVNNNNNNNDDDDDDDDVKZZTTTTTTTTOJYYYYYWWWWWWWGGGGGCAAAHPCGGDGHHHQQQQHQQQ\n" +
                "MMMBBBBBBBBBBBBBBBJJOOOOOOOOOOOOOOOOMMMMMGGGGGGGGGGIIIIKKKKKKKKKKVVVVVVVNNNNNNNNNDDDVVVVKKKTTTTTTTTJJYYYYYYYYWWWZGGGGGGAAAPPPIIGGHHHHUQQQQQQ\n" +
                "MMBBQQBBBBBBBBBBBJJJJOOOOOOOHHHVVOKOMMMMMIIIIIIIIIIIIIIKKKKKKKKKKKVVVVVVNNNNNNNNNDDVVVVVKTTTTTTTTTTJJYYYJYYYYYYGGGGGGAAAAAPPPIIPPAAHHUUUCQQQ\n" +
                "MQQQQQBBBBBBBBJJBJJJJJJOOOOHHHHHVVKKMMPMKKKAIIIIIIIIKKKKKKKKKKKKVVVVVVVVVNNNNCNNDVVVVVVVVTTTTTTTTTTJJJJJJYYYYYGGGGGGGGGAAAPPPPPPPAAHHUUUCCCQ\n" +
                "MQQQBBBBBBBBBJJJJJJJJJJJJOHHHHHHHVKKMKKKKAZAIIAAIIIIKKFKKKKKKKXXXVKVVVVVDDNNNCCCVVVVVVVVVTTTTTTTTTTJJJJJJYYYYYGGGGGGGPPPPPPPPPQPPACCCCCCCCCQ\n" +
                "MQQQBQBBBBBBBJJJJJJJJJJJOOHHHHHHHHKKKKKKKAAAAAAAIAIIFKFFKKKKXXXXXKKKVVDDDDNNDVVVVVVVVVVVVTTTTTTTJJJJJJJJJJYYYYGGGGGGGGGPPPPPPPPPPAACCCCCCCCC\n" +
                "QQQQQQQBBBBBBJJJJJJJJJJJJOHHHHHHHHHKKKKKKAAAAAAAAAAAFFFFKKKKXXXXXKKKVVDDDDDDDDVVVVVVVVVVVTTTTTTTJJJJJJJJJYYYYYGGGGGGGGGGPPPPPPPPPPAACCCCCCCY\n" +
                "QQQQQQQQJBBBBBJJJJJJJJJJOOOHHHHHKHKKKKKKKAAAAAAAAAAAFFFFXXXXXXXXXKKKVVDDDDDDVDVVVVVVVVVVVTTTTTTTJJJJJJJJJJJYYYGGGGGGGGGGGPPPPPPPPPPCCCCCCCYY\n" +
                "QQQQQQQBBBBBBJJJJJJJJJJJOOOFFFFKKHKKKKKAAAAAAAAAAAAAFFFFXXXXXXXXKKKVVVDDDDDDVVVVVVVVVVVVJTTTTTTTYYJJJJJJJJYYYYYGGGGGGGGGPPPPPPPPPPCCCCCCCYYY\n" +
                "QQQQQQQQQBBBBBJJJJJJJJJJOOOOOFFKKKKKAAAFAAAAAAAAAAAFFCCCXXXXXXXXKKVVVDDDDDDDVVVVVVVVVVVVJTTTTTTTJYJJJJJJJJJYYYGGGGGGZGGVPPPPPPPPPPCCCCCCCYYY\n" +
                "QQQQKKQQQQBBBJJJJJJJJJJEOOOOFFFAKKKAAAAAAAAAAAIIIIIIFFFCXXXXXXXXXXXXXXXDDDDDVVVVVVVVVVVVYTTTTTTTJYYJJJJJJYYYYYYGGGGGZZUZPPPPPPPPPCCCCCCCCCYY\n" +
                "QQQQQKKKQQBBBJJJJJJJXNNEEOOOOAAAACAAAAAAAAAAAAIIIIIICCCCXXXXXXXXXXXXXXXDDDDDVDVVVVVVVVVVYYYYYYJJJYYYJJJJJYYYYYYYGGZGTZUZBPPPPPPPPVCCCEEEECYY\n" +
                "QQQQLBBKKBBBBBJJJJJJXNNNOOOQQQQAAAAAAAAYAAAAAAIIIIIIPPCCXXXXXXXXXXXXXXXRRDDDDDVDDVVVVVVVYYYYYYYYYYYYYYYYYYYYYYYYYZZZZZZZZPPPPPPPPVCCCEEEEEYY\n" +
                "QQQQBBBBBBBBBBJJJJJJJNNOOQQQQQQAAAAAAAAAAAAAAAIIIIIIPACCXXXXXXXXXXXXXXXRRDDDDDDDDVVVVVVVYYYYYYYYYYYYYYYYYYYYYYYYYYZZZZZZZUPEPEPPPPCCEEEEEYYY\n" +
                "AAAABBBBBBBBBBJJJJJJJJJQQQQQQQAAAAAAAAAAAAAAAAIIIIIIAAFYCCCCCCXXXXCYDDDDDDDDDDDDDDDVVVNNYYYYYYYYYYYYYYYYYYYYYYYYYYZZZZZZZUEEEEEPPEEEEEEEEEYY\n" +
                "AAAAABBBBBBBBBBJJJJJJJQQQKQQQQAAAAAAAAAAAFAAAAIIIIIIFFFCCCCCCCXXXXCYDDDDDDDDDDDDDDNNNNNNNYYYYYYYYYYYYDDDDYDDYYYYZZZZZZZZZZEEEEEEEEEEEEEEEEEY\n" +
                "AAAAAVABBBBBBBBQJJJJJQQQKKKQKAAWAAAAAAAAAAAAAAIIIIIIFNFNNNNNNNCCCCCYYDDDDDDDDDDDDDDNNNNNNYYYYYYYYYYYDDDDDDDYYYYYZZZZZZZZZZZEEEEEEEEEEEEEEEEY\n" +
                "AAAAAAABBBBBBBBQQJJJQQQQQKKKKKAWWAAAAAMMAAAAAAIIIIIIFNFNNNNNNNCYCYYYYDDDDDDDDUDDDDDDDNNNNYYYYYYYYYYYDQDDDDDYYYYZZZZLZZZZZZZEEEEEEEEEEEEEEEEY\n" +
                "AAAAAAAAAAAABBBQQQQQQQQQQQKKKKWWWAAAAAAAAAAAAAIIIIIIFFFNNNNNNNCYCYYYYYDDDDDDDDIIIDDDDNNNYYYYYYGYYYYDDQDXXDDDDYYZLLLLZZZZZZZEEEEEEEEEEEEEEEEY\n" +
                "AAAAAAAAAAAEBBQQQQQQQQQQQQQQKWWWWWWAAAAAAAAAAAAAFFFFNNNNNNNNNNYYYYYYYYYYDDWDDDDIIDDDDDNYYYYTYYYYYYYYQQQXXDDDXYYZLLLLLLZZZZEEEEEEEEEEEEEEEEEY\n" +
                "AAAAAAAAAAEEBBGQGQQQQQQQQCCCKCWCCCWWWWWAAHAAAAAAFFFFNNNNNNNNNNYYYYYYYYYDDWWYDLDDIIIDDDDHHQQQYZYYYYQQQQXXXDDDXLYXLLLLLZZZVZEEEEEEEEMEEEEEMMMM\n" +
                "AAAAAAAAAAEEEGGGGGQGGGQQQCCCCCCCCWWWWWWAAAAAAAAAFFFFNNNNNNNNNNQYQQQYYYYYYYYYGDDDDDDDDDDDHQQQQQQQQYQQQQQXXXDDXXXXLHHHLZVVVZEEEEEEEEMEEEMMMMMM\n" +
                "AAAAAAAAAAEEGGGGPGGGGGCCCCCCCCCCCRRRRWWWWWWFFFAFFFFFNNNNNNNNNNQQQQQYYYYYYYYYGDDDDDDDDDDQQQQQQQQQQQQQXXXXXXXXXHHXHDHHLZZZZZEEEEEEMMMEEMMMMMMM\n" +
                "AAAAAAAAAWGGGGGGGGGGGGGCCCCCCCCCCRRRRWWWWWWWWFAFFFFFNNNNNNNNNNYYQQQQQYYYYYYYGGDDDDDDDRDQQQQQQQQQQQQQXXXXXXXXXHHHHHHHLLLEEEEEEEEMMMMMMMMMMMMM\n" +
                "AAAAAAAUAWWGGGGGGGGGGDCCCCCCCCCCCRRRRRRWWWWWWFFFFFFFNNNNNNNNNNYYQQQQQYJYYYYYYGDDDDDDFFQQQQQQQQQQQQQXXXXXXXXXXHHHHHHHLLLEEEEEEEEMMMMMMMMMMMMM\n" +
                "AAAAAAAAAAAGGGGGGGGGCCCCCCCCCCCXCCRRRRWWWWWWWWWDFFFFNNNNNNNNNNYQQQQQYYJYYYYDDDDDDDFDFFFQQQQQQQQQQQXXXXXXXXHHHHHHHHHHHHHEEEEEWWEMMMMMMMMMMMMM\n" +
                "AAAAAAAAAAGGGGGGGGGGGCCCCCXCCICXXKKRRWWWWWWWWWDDFFKKNNNNNNNNNNQQQQQQYJJYYYYDDDDDDFFFFFFCCCCCCCCQQQXXXXXXXXHRHHHHHHHHHZZNZZEEEWWMMMMMMMMMMMMM\n" +
                "AAAAAAAAAAGGGGGGGGGGCCLCCCCCCCKXKKKWWWWWWWWWWWWDFKKKNNNNNNNNNQQTQRQQQJJYYYYDDDDDDFCCCCCCCCCCCCCQQQQQXXXXXXXXHHHHHHZZZZZZZZZEEWWAMMMMMMMMMMMM\n" +
                "IIIIAAIAAAAIGGGGGGGGGCLCCCCCOCKKKKKKWWWWWWWWWWWDDKKKKKKKKKKKKQQQQRRQTTJJYYYDDDDDFFCCCCCCCCCCCCCQQQXXXXXXXXXXHHHHHHZZZZZZZZZZWWWMMMMMMMMMMMMM\n" +
                "IIIIIIIIAIAIAGGGGGGGGGLNNNCCOOOKKKKKKKKKKWWWWWWWWKKKKKKKKKKKKQQQQQQTTTTJYHYRRRRFFFCCCCCCCCCCCCCQQQQXXXXXXXBBBHHHHZZZZZZZZZZZZWJMMMMMMMMMMMMM\n" +
                "IIIIIIIIIIIIIGGGGGGGGGNNNNCNNONKKKKKKKZKSWWWWWWWWWKKKKKKKKKKKQQQQQQQTTTTTYYRRRRRRFCCCCCCCCCCCCCQQQQXXXXXXXBBHHHZZZZZZZZZZZZZWWWMMMMMMMMMMMMM\n" +
                "IIIIIIIIIIIIIGGGGGGGGGNNNNNNNNNZKKKKKKKSSWWWWWWWWWWKKKKKKKKKQQQQQQQQTTTTTTTUURRRRFCCCCCCCCCCCCCQQQQQXXXXXXXXZHHZZZZZZZZZZZZZZWWWWWMMMMMMMMMS\n" +
                "IIIIIIIIIIIIRAAAAANNGNNNNNNNNNNKKKKKKKSSLWWWWWWWWWWMKKKKKKKKQQQQQQQQQQUUUTUUUURFRFFFCCCCCCCCCCCQQQQQXXXXXXXZZZZZZZZZZZZZZZZZZWWWWWMWWGMMMMMS\n" +
                "IIIIIIIIIIIIAAAAAANNNNNNNNNNNNNKKKKKKKKSLLWWWWWWMWWYKKKKKKKKYQQQQQCQQQUUUTUUUUUFFFFFFFFFFFHHHHHHHHHHXXXXXBXXZZZZZZZZZZZZZZZOZWWWWWWWGGMGMMMG\n" +
                "IIIIIIIIIIIAAAAAAAANNNNNNNNNNNNKKKKKKKLSLLWWCWMMMYYYKKKKKYYYYQQQQQCQQQUUUUUUUUUUFFFFFFFNFHHHHHHHHHHXXXXXXXXXXZZZZZZZZZZZZZZOZZZWWWWWGGGGMGVG\n" +
                "IIIIIIIIIIIAAAAAAANNNNNNNNNNNNNXXKKKLLLLLLLWWMMMYYYYYKYKYYYYYQQQCCCCCQUUUUUUUUUUPFFFFFFFFHHHHHHHHHZZZZAAXXXXXZZZZZZZZZZZZZZZZUUWWWWGGGGGGGGG\n" +
                "IIIIIIIIIIIAAAAAAANNNNNNNNNNNNXXXKKKKLLLLLLMMMMMYYYYYYYYYYYYYQQCCCCCCCUUUUUUUUUUFFFFFFFFFFHHHHHHHZZAAAHAAAXXZZZZZZZZZZZZZZZUUUUUUGGGGGGGGGGG\n" +
                "YIIIIIIIIIIAAAAAAANNNNNNNNNNNNXXXKKKKLLLLLLLMMMMMYYYYYYYYYYYYYYYCCCCCCUUUUUUUUUUFFHFFFFFFHHHHHHHHHZAAAAAAAXXXZZZZZZZZZZZZZZZUUUUUGGGUGGGGGGG\n" +
                "YYIIIIIIIIAAAAAAAANNNNNNNNNNXXXXXXXXXLLLLLLLMMMMMMYYYYYYYYYYYYCCCCCCCCRRUUUUUUUUGFHHHHHHHHHHHHHHHHAAAAAAAAAXXZZZZZZZZZZZZZZZUUUUUUGGGGGGGGGG\n" +
                "YYYIIIIIIIAAAAAAAAANNNNNNNNNNXXXXXXXXLLLLLLLLMMMMMYYYYYYYYYYYYYYCCCCRRRRRUUUCCUUGHHHHHHHHHHHHAHAKKAAAAAAAAAXXZZZZZZZZZZZZZUUUUUUGGGGGGGGGGGG\n" +
                "YYYYINNIIIAAAAAAAAANNNNNNNNXXXCXXXXXXXLLLLLLMMMMMYYYYYYYYYYYYYYRRRRRRRRRRUCUCCCCHHHKHHHHHHHHHAAAAAAAAAAAAAAAXZZZZZZZHHZZZZUUUUUUGGGGGGGGGGGG\n" +
                "YYYYINIIIAAAAAAAAAAAAQNONICCCXCCXXXXXXXXLLLLMMMMMMYYYYYYYYYYYYRRRRRRRRRRRCCCCCCZZHHHHHHTTHHHHHAAAAJAAAAAAAAAAEZZZZZHHHZZZZUUUUUUGGGGGGGGGGGG\n" +
                "YYYYYAAAAAAAAAAAAAAAANNQQQCCCCCCXXXXXXXXLMMLMMMMMMYYYYYYYYYYYYRRRRRRRRRRCCCZZCCZZTTTTTTTTTHHHHAJJJJAAAAAAAAAAAZZZZZZHHZZZZUUUUUUGGGGGGGGGGGG\n" +
                "YYYYYAAAAAAAASSAAAAAAIQQQQCCCCCCXXXXXXXXLMMMMMMMMMMMMMMYZYRRYRRRRRRRRRRRZCCZZZCCZZTTTTTTCTHHHHHHJJJAAAAAAAAOOOZZPPPOHUUCUUUUUUUUUGGGGGGGGGGG\n" +
                "YYYEEEEAAAAASSSAAAAAAQQQQCCCCCCCCCCXXXXXLMMMMMMMMMMMWWMWRRRRYYRRRRRRRRRRZZZZZZZZZBTTTTTPTTHHHHHHHJJJJAAXAAAAAZZZPOOOOOUUUUUUUUGGGGGUGGGGGGGG\n" +
                "YEEEEEEAAAAASSAAAAAAQQQQQCCCCCCCCCCCCXXXLMMMMMMMWWMWWWMWRRRRRRRRRRRGRRRZZZZZZZZZZZTTTTTTTTTTHHHHHJJJJAAAAMMMMMZZZHHOONNUVUUUUUGGUGUUUGGGGGGG\n" +
                "YEEEEEEDAAASSSAAKQQAQQQVQCCCCCCCCCCCXXXKKMMMMMMMWWWWWWWWRRRRRRRRRRRRRRZZZZZZZZZZZZZTTTTTTTTTTJJJJJJJJJAAMMMMMMMZZHHOOONVVVVUUUUUUGUUKGGGGGZG\n" +
                "YEEEEEAAAAAASSKKKQQQQQVVQCCCCCCCCCCCCKXKMMMMMMMMMMWWWWWWRRRRRRRRRRRRRZZZZZZZZZZZZZZTTTTTTTTTTTJJJJJJJJJTMMMMMMMZZHHOVVVVVVVVUUUKUUUUKKGGGGGG\n" +
                "EEEELEEEGAASSSSCKKVQQVVVHCCCCCCCCCCCKKKKKKKMMMMMWWWWWWWPWRRRRRRRRRRRIMMZZZZZZZZZZTTTTTTTTTTTTTJJJJJJJJTTTMMMMMMZJJHHHHHVVVVVVKUKKKUUKKKKKGUU\n" +
                "NEEEEEEEEARWSSSSTKVVVVVVHCCCCCCCCCCKKKKKKKKKMMMMWWWWWWWWWRRRRRRRRIIRIMMZZZZZZZZZZTTTTTTTTTTTTJJJJJJJJJTTTTMTTTTTJJJHHHHVVVVVKKKKKKKKKKKKKKKU\n" +
                "EEEEEEEERRRWWSSSSSSVVVVVHCCCCCCCCCCKKKKKKKKKKMMMMWWBWWWWWRRRRRRRRBBBBBBBBBBZZZZZZTTTTTTTTTTTTJJJJJJJJJTTTTTTTTTTTHHHHHHVVVVVKKKKKKKKKKKKKKKK\n" +
                "HEEEEEEERWWWWHHSSSSSVVVVVVCCCOCCCCKKKKGKKKKKKMMMMMWBWWWWWRRRRRRRRBBBBBBBBBBZZZZLZTTTTTTTTTTJJJJJJJJJTTTTTTTTTTTTTTHHHHVVVVVVKKPKKKKKKKKKKIII\n" +
                "EEEEEEEEERWWWHHSWSSSSVVVVVCCCCCKKKKKKKKKKKKKMMMBBBBBBWWWBRRRRRRRRBBBBBBBBBBZYZZTTTTTTTTTTTTTCJCJJZZJTTTTTTTTTTTTTTTHHVVVVVVKKKKKKKKKKKKKKIII\n" +
                "EEEEEEEEEEEWWWWWWVVVVVVVVVVVCCCKKKKKKKKKKKKQBBBBBBBBBBBVBRRRRRRRIBBBBBBBBBBZZZXTTTTTTTTTTCTCCCCJCZZNTTTTTTTTTTTTTTTHHVVVVVVKKKKKKKKKKYKKIIII\n" +
                "EEEEEEEEEEEWWWWWWVVVVVVVVVVVVCKKKKKKKKKKKKIQBQBBBBBBBBBBBBBRRRRRBBBBBBBBBBBZXXXGKTTTTTTTTCCCCCCCCCNNTNTTTTTTTTTCVVVVVVVVVVVKKKKKKKKKKYYYYIII\n" +
                "EEEEEBBEEWWWWWWWWVVVVVVVVVVVVVVKKKKKKKKKKIIQQQQBBBBBBBBBBBBRUUUUUBBBBBBBBBBIXXXGGTTMTTTTTCCCFFFFFFFNNNTTTTTTTTTVVVVVVVVVVVVVVKKKKKKKKKKYYYII\n" +
                "EEEEEBBBEWWWWWWWWVVVVVVVVVVVVVVVKKKKKKKKKIIIQQBBBBBBBBBBBBRRUUUUUBBBBBBBBBBIXXXGCTTMMTTTTCCCFFFFFFFNNNNNTTTTDTNVVVVVVVVVVVVVVKKVKKKKYKHYYYII\n" +
                "LBEBBBBBJWWWWWWWVVVVVVVVVVVVVVKKKKKKKKKKIIIIIINTBBBBBBBBBBRRUUUUUBBBBIIIIIIIIGGGGGMMMCTCCCCCFFFFFFFNNNNNDDTDDDDVVVFVTTTVTVVVVKVVVYYYYYYYYYYY\n" +
                "BBBBBBBBJJJWWWWWWWVVVVMVVVVVVVKKKKKKKKKKKKIIIINTBBBBBBBBBRRRUUUUUBBBBIIIIIIIIIGGGGGMMCCCCCCCFFFFFFFNNDDDDDDDDDDDDTTTTTTTTVTTVVVVVVVYYYYYYYYY\n" +
                "BBBBBBBBJJJJJWWWWWWGGGVVVVVVVKKKOKKKKKKKKKIIINNNBBBBBBBBBRRRUUUUUBBBBIIIIIIIIIGGHMMMCCCCCCCCFFFFFFFNNDDDDDDDDDDDDCTTTTTTTTTTVVVVVVVYYYYYYYYY\n" +
                "BBBBBBBJJJJJWWWWWWWWGGGGVVVVVKKOOOKKKKKKKKKIKKNUUUUBBBBBBRRRUUUUUBBBBIIIIIGGGGGHHHCCCCCCCCCCCCCCOOODDDDDDDDDDDDTTTTTTTTTTTTTVVVVVYYYYYYYYYYL\n" +
                "BBBBBBJJJJJJJWWWWQQQGGGGVVVVKKKOOOOKKKKKKKKKKKUUUUUBBHBBBBRRJJJJBBBBBIIIIIGGGGHHHHHCCCCCCCCCCCCCOOOODDDDDDDDDDDTTTTTTTTTTTTTTVVVVVYYYYYYYYYY\n" +
                "BBJJJJJJJJJJJWWQQQQQQGGGGVGGGKOOOKKKKKKKKKKKKKUSSUUUJUBBBURRYYYJJJIIIIIIIIGGGGHHHHHHHHCCCCCCCCCOOOOOODDDDDDDDDTTTTTTTTTTTTTTTVVAAVYYYYYYYYYY\n" +
                "BBJJJJJJJJJJWWQQQQQQGGGGGGGKKKKKOKKKKKKKKKKOKKUUUUUUUUBBUUUQQYYJJJIIIIISIIIGGGGHHHHHHHHCHCCCCCCCOOOODDDDDDDDDDTTTTTTTTTTTTTTAVAAAYYYYYYYYYYY\n" +
                "JJJJJJJJJJJJJWWQQQQQGGGGGGGGKKKKKKKKKKKKKKKOOKUUUUUUUUUUUUUQQQJJJJIIIIIGGIGGGGGHHHHHHHHHHCCHCCCCCCCDDDDDDDDDDDDTTTTTTTTTTTAAAAAAAAYYYYYYYYYY\n" +
                "JJJJJJJJJJJJWWWQGQGQGGGGGGGGGKKCKKKKKKKKKOOOOJUUUUUUUUUUUUQQQVQJJIIIIIZZGGGGGGGHHHHHHHHHHHHHCGCCCBKBPDDDDSDDDDDTTTTTTTTTTTTTAAAAAAYYYYYYYYYU\n" +
                "JJJJJJJJJJJJJJBGGGGGGGGGGGGGGKCCKKKKKKKKKOOOOOUUUUUUUUUUUUQQQQQJJJIZZZZZGGGGGGGHHHHHHHHHHHHCCGCBBBBBBSDGDDDDDDTTTTTTTTTTTTTTAMAAAAYYYYYYYYYU\n" +
                "JJJJJJJJJJJBJJBGGGGGGGGGGCCGCCCCCKKKKKKKAOOOOOOUUUUUUUUUUUQQQQQQZZIZZZTZGGGGGGGHHHHHHHBHHHHBBBBBBBBBDDDDDEEDDDEQQLTTTTTTTTTCMMAYYYYYYYYYYYYU\n" +
                "JBJJJJJJJJJBBBBBGGGGGGGGGCCCCCCCCCCCKKKAAOOOOOOOOUUUUUUUUUQQQQQQQZZZZZXXXGGGGGGHHHHHHHBBBBBBBBBBBBBBBDDDDEEEDEEQQQIIITTTTTTTTMMMYCYYYYYYUUUU\n" +
                "BBBBJLLLQJBBBBBBBGGGGGGGGGCHHCCCCCCCWKKKAAOOOOOOOOOOUUUUUUQQQQQQQZZZZXXXZZZGGHHHHHHMBBBBBBBBBBBBBBBBDDDDDEEEEEQQQQIQITTTKTTTMMMMMCYYYYYUUUUU\n" +
                "BBBBJLLLLLLBBBBBBGGGGGGGGGGHHCCCCCCCCKAAAOOOOOOOOOOOUUUUUUQQQQQZZZZZZXXXZZZZGGHMMHHMBBBBBBBBBBBBBBBQDDDDDEEEEEEQQQQQITTTKKKTMMMMMCYYYYYUUCUC\n" +
                "BBBBBBLLLBBBBBBBBGGGGGGGGGCCCCCCCCCCCAAAAOOOOOOOOOOOOOOUUUTQQQQZZZZZZZZZZZZZGGGGMMMMBBBBBBBBBBBBBBBQDDDDEEEEEEQQQQQQQKKKKKKMMMMMCCCCCCCCCCCC\n" +
                "BBBBBLLLLLBBBBBBBBBBGGGGGGCCCCCCCCCAAAAAOOOOOOOOOOOOOOOOCCOQQZQZZZZZZZZZZZZZGGGGMMMMBBBBBBBBBBBBBBBDDDDDDEEEEEEQQQQKQKKKKKKMMMMMCCCCCCCCCCCC\n" +
                "BBBBBBBBBBBBBBBBBBBGGGGNGJJJCCCCCCAAAAAAOOOOOOOOOOOOOOOOOOOZZZZZZZZZZZZZZZZZZZZZMMMMMBBBBBBBBBBBBBBTTTTDEEEEEEEEEQKKKKKKKKKMMMMMMMMCCCCCCCCC\n";


        String[] ss = t.split("\n");
        char[][] mat = new char[ss.length][ss.length];
        int[][] visit = new int[ss.length][ss.length];
        for (int i = 0; i < ss.length; i++) {
            for (int j = 0; j < ss[0].length(); j++) {
                mat[i][j] = ss[i].charAt(j);
            }
        }
        int result = 0;
        int totalArea = 0;
        for (int i = 0; i < visit.length; i++) {
            for (int j = 0; j < visit[0].length; j++) {
                if (visit[i][j] == 0) {
                    int[][] box = new int[visit.length][visit[0].length];
                    int x = visitMe(mat, visit, i, j, mat[i][j], box);
                    totalArea += x;
                    result += x * getSides(box);
                }
            }
        }

        System.out.println(totalArea);
        System.out.println(result);
        System.out.println("here");

    }

    private static int getSides(int[][] box) {

        int sides = 0;
        //TODO : nr of sides of a shape
        return sides;
    }

    private static int visitMe(char[][] mat, int[][] visit, int i, int j, char c, int[][] box) {

        if (i < 0 || j < 0 || j == mat.length || i == mat.length) {
            return 0;
        }

        if (visit[i][j] == 1) {
            return 0;
        }

        if (mat[i][j] != c) {
            return 0;
        }
        visit[i][j] = 1;
        box[i][j] = 1;
        return 1 + visitMe(mat, visit, i + 1, j, c, box) + visitMe(mat, visit, i, j + 1, c, box) + visitMe(mat, visit, i, j - 1, c, box)
                + visitMe(mat, visit, i - 1, j, c, box);

    }
    // 1461806


}
