package adventofcode.aoc2022.day2;

public class Solution {

    public static void main(String[] args) {
        String s = "B Z\n" +
                "A Z\n" +
                "B Z\n" +
                "C Z\n" +
                "C Z\n" +
                "B X\n" +
                "A X\n" +
                "C X\n" +
                "A Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "B Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "C X\n" +
                "C Z\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "B X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "C Z\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "C X\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "C X\n" +
                "B Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "C X\n" +
                "C Y\n" +
                "B X\n" +
                "C Z\n" +
                "A Z\n" +
                "C X\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A X\n" +
                "C X\n" +
                "A X\n" +
                "C Y\n" +
                "C X\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "C X\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "C X\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C X\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "B Y\n" +
                "B X\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "B X\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "B Z\n" +
                "C X\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C X\n" +
                "A Z\n" +
                "A Z\n" +
                "C X\n" +
                "B X\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "C X\n" +
                "A Z\n" +
                "C Z\n" +
                "C Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A Z\n" +
                "C X\n" +
                "A X\n" +
                "B Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C X\n" +
                "B X\n" +
                "A Z\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "B X\n" +
                "C Z\n" +
                "B X\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "A Z\n" +
                "C X\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A Z\n" +
                "C X\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "C X\n" +
                "A X\n" +
                "C X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "C X\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "C X\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "C X\n" +
                "A X\n" +
                "A Z\n" +
                "B X\n" +
                "C Z\n" +
                "A Y\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B Y\n" +
                "A Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "B Y\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "B Y\n" +
                "C X\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "A Z\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "A X\n" +
                "B X\n" +
                "A Z\n" +
                "C X\n" +
                "A Z\n" +
                "A X\n" +
                "C X\n" +
                "B X\n" +
                "B Y\n" +
                "B X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "B X\n" +
                "B X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Y\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C X\n" +
                "C Y\n" +
                "A X\n" +
                "C X\n" +
                "C X\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "C X\n" +
                "A Z\n" +
                "A Z\n" +
                "C X\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Z\n" +
                "C Z\n" +
                "B Z\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "B X\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "B X\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "C X\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "C X\n" +
                "A X\n" +
                "C X\n" +
                "A X\n" +
                "C X\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "B Y\n" +
                "A X\n" +
                "B Z\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "C X\n" +
                "B X\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Y\n" +
                "C X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "C X\n" +
                "C Z\n" +
                "B Y\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "C X\n" +
                "A Z\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "C X\n" +
                "B Z\n" +
                "A Z\n" +
                "A Y\n" +
                "C X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C X\n" +
                "A Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C X\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "A Z\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A Z\n" +
                "B Y\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B X\n" +
                "C Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "C X\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "C X\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "C X\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "B Y\n" +
                "B Y\n" +
                "C X\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A X\n" +
                "C Z\n" +
                "B X\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C X\n" +
                "A Z\n" +
                "B Z\n" +
                "C X\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C X\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C X\n" +
                "A Z\n" +
                "B X\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "B X\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "B Y\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C X\n" +
                "A X\n" +
                "A X\n" +
                "C X\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "A Z\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "A Y\n" +
                "A X\n" +
                "A Z\n" +
                "C X\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "C X\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "B Y\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C X\n" +
                "A Z\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "B Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B X\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A Y\n" +
                "A Z\n" +
                "B Z\n" +
                "C X\n" +
                "A Z\n" +
                "A Z\n" +
                "B X\n" +
                "A X\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C X\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "B Z\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C X\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A Z\n" +
                "C Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "B X\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "B Z\n" +
                "A Z\n" +
                "C X\n" +
                "B Z\n" +
                "C X\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C X\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C X\n" +
                "B Y\n" +
                "B Y\n" +
                "C X\n" +
                "C Y\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C X\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C X\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "B X\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "B X\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "C X\n" +
                "A Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B X\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C X\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "B Y\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "C X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "B Y\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C X\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C X\n" +
                "B X\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "C X\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C X\n" +
                "A Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "C X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "C X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C X\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "B Y\n" +
                "C X\n" +
                "B X\n" +
                "B X\n" +
                "A Z\n" +
                "A Y\n" +
                "B Y\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "C X\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C X\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "C X\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Y\n" +
                "C X\n" +
                "A X\n" +
                "A Y\n" +
                "C X\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "C X\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Z\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "B Y\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A X\n" +
                "C X\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "C X\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "C Z\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "C X\n" +
                "B Y\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "B X\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "B Y\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C X\n" +
                "B X\n" +
                "C Z\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "C X\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "B X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "C X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "C X\n" +
                "B Z\n" +
                "A Z\n" +
                "A X\n" +
                "B Y\n" +
                "A Z\n" +
                "A X\n" +
                "C X\n" +
                "C X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "B Z\n" +
                "B Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "C X\n" +
                "C Y\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "C X\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "C X\n" +
                "B Y\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "A Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "C X\n" +
                "B X\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "C Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "B Y\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "B X\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "C X\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "B Y\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "C X\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "B X\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "B X\n" +
                "A Z\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "A Z\n" +
                "A Z\n" +
                "B X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "C X\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "B Y\n" +
                "C X\n" +
                "A X\n" +
                "A Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "C X\n" +
                "B X\n" +
                "A Z\n" +
                "C Z\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "B X\n" +
                "C X\n" +
                "A Y\n" +
                "A X\n" +
                "A Z\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "A Z\n" +
                "A X\n" +
                "C X\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "C X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "C X\n" +
                "C Z\n" +
                "B X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "B X\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "B Y\n" +
                "C Y\n" +
                "C X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B X\n" +
                "C X\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "C X\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "C X\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "B Z\n" +
                "B X\n" +
                "A Z\n" +
                "A X\n" +
                "C X\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Z\n" +
                "A X\n" +
                "B X\n" +
                "C X\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C X\n" +
                "A Z\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "C X\n" +
                "A Y\n" +
                "C X\n" +
                "C X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "B Y\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n";

//        String t = "A Y\nB X\nC Z";
        String[] ss = s.split("\n");
        long sum = 0;
        for (int i = 0; i < ss.length; i++) {
            String[] tt = ss[i].split(" ");
            int score = evaluateWin(tt[0], tt[1]);
            sum += evaluatePiece(tt[1]);
            sum += score;
        }
        System.out.println(sum);

    }

    private static long evaluatePiece(String s) {
        if (s.equals("X")) {
            return 1;
        }
        if (s.equals("Y")) {
            return 2;
        }
        return 3;
    }

    private static int evaluateWin(String s, String s1) {
        if (s.equals("A")) {
            if (s1.equals("X")) return 3;
            if (s1.equals("Y")) return 6;
            return 0;
        }
        if (s.equals("B")) {
            if (s1.equals("Y")) return 3;
            if (s1.equals("Z")) return 6;
            return 0;
        }
        if (s.equals("C")) {
            if (s1.equals("Z")) return 3;
            if (s1.equals("X")) return 6;
            return 0;
        }
        return 0;
    }
}
